use super::*;

impl SettingsView {
    pub(super) fn render_process_page(&mut self, cx: &mut Context<Self>) -> gpui::AnyElement {
        let snapshot = self.process_snapshot.clone();
        let process_groups = Self::group_processes(&snapshot.processes);
        let process_loading = self.process_loading;
        v_flex()
                            .w_full()
                            .gap_3()
                            .child(
                                v_flex()
                                    .w_full()
                                    .gap_3()
                                    .p_4()
                                    .rounded(crate::ui::design::r_lg())
                                    .border_1()
                                    .border_color(crate::ui::design::line_2(cx))
                                    .bg(crate::ui::design::surface(cx).opacity(0.55))
                                    .child(
                                        h_flex()
                                            .w_full()
                                            .items_center()
                                            .gap_2()
                                            .child(
                                                v_flex()
                                                    .flex_1()
                                                    .min_w(px(0.))
                                                    .gap_0p5()
                                                    .child(
                                                        h_flex()
                                                            .gap_3()
                                                            .flex_wrap()
                                                            .text_size(crate::ui::design::text_body())
                                                            .child(format!(
                                                                "Choro {}",
                                                                Self::format_bytes(snapshot.app_bytes)
                                                            ))
                                                            .child(format!(
                                                                "Related {}",
                                                                Self::format_bytes(snapshot.total_bytes)
                                                            ))
                                                            .child(format!("CPU {:.1}%", snapshot.total_cpu)),
                                                    )
                                                    .child(
                                                        div()
                                                            .text_size(crate::ui::design::text_ui())
                                                            .text_color(crate::ui::design::t3(cx))
                                                            .child(format!(
                                                                "PID {} · {} related process{} including web content, agents, terminals, and scripts",
                                                                snapshot.root_pid,
                                                                snapshot.process_count,
                                                                if snapshot.process_count == 1 { "" } else { "es" },
                                                            )),
                                                    ),
                                            )
                                            .when(process_loading, |row| {
                                                row.child(Spinner::new().xsmall())
                                            })
                                            .child(
                                                crate::ui::style::refresh_button(
                                                    "refresh-process-monitor",
                                                    "Refresh",
                                                    cx,
                                                )
                                                    .disabled(process_loading)
                                                    .on_click(cx.listener(|this, _, _, cx| {
                                                        this.refresh_process_snapshot(cx);
                                                    })),
                                            ),
                                    )
                                    .when_some(snapshot.error.clone(), |card, error| {
                                        card.child(
                                            div()
                                                .text_size(crate::ui::design::text_ui())
                                                .text_color(crate::ui::design::rose(cx))
                                                .child(SharedString::from(error)),
                                        )
                                    })
                                    .when(snapshot.error.is_none(), |card| {
                                        card
                                            .child(
                                                div()
                                                    .text_size(crate::ui::design::text_ui())
                                                    .text_color(crate::ui::design::t3(cx))
                                                    .child(SharedString::from(
                                                        snapshot.measurement_note.clone(),
                                                    )),
                                            )
                                            .when(!snapshot.categories.is_empty(), |card| {
                                                card.child(
                                                    v_flex()
                                                        .w_full()
                                                        .gap_2()
                                                        .pt_2()
                                                        .border_t_1()
                                                        .border_color(crate::ui::design::line(cx))
                                                        .child(
                                                            v_flex()
                                                                .gap_0p5()
                                                                .child(
                                                                    div()
                                                                        .text_size(crate::ui::design::text_body())
                                                                        .font_weight(FontWeight::SEMIBOLD)
                                                                        .child("Inside Choro"),
                                                                )
                                                                .child(
                                                                    div()
                                                                        .text_size(crate::ui::design::text_ui())
                                                                        .text_color(crate::ui::design::t3(cx))
                                                                        .child("The allocation types that make up Choro's own memory."),
                                                                ),
                                                        )
                                                        .children(snapshot.categories.iter().map(|category| {
                                                            let display_name = Self::memory_category_name(&category.name);
                                                            let raw_name = category.name.clone();
                                                            h_flex()
                                                                .w_full()
                                                                .gap_2()
                                                                .items_center()
                                                                .text_size(crate::ui::design::text_ui())
                                                                .child(
                                                                    div()
                                                                        .w(px(82.))
                                                                        .font_weight(FontWeight::MEDIUM)
                                                                        .child(Self::format_bytes(category.bytes)),
                                                                )
                                                                .child(
                                                                    v_flex()
                                                                        .flex_1()
                                                                        .min_w(px(0.))
                                                                        .child(SharedString::from(display_name.clone()))
                                                                        .when(display_name != raw_name, |column| {
                                                                            column.child(
                                                                                div()
                                                                                    .truncate()
                                                                                    .text_color(crate::ui::design::t4(cx))
                                                                                    .child(SharedString::from(raw_name.clone())),
                                                                            )
                                                                        }),
                                                                )
                                                                .child(
                                                                    div()
                                                                        .flex_none()
                                                                        .text_color(crate::ui::design::t4(cx))
                                                                        .child(format!("{} regions", category.regions)),
                                                                )
                                                        })),
                                                )
                                            })
                                            .child(
                                                v_flex()
                                                    .w_full()
                                                    .gap_2()
                                                    .pt_2()
                                                    .border_t_1()
                                                    .border_color(crate::ui::design::line(cx))
                                                    .child(
                                                        v_flex()
                                                            .gap_0p5()
                                                            .child(
                                                                div()
                                                                    .text_size(crate::ui::design::text_body())
                                                                    .font_weight(FontWeight::SEMIBOLD)
                                                                    .child("Related processes"),
                                                            )
                                                            .child(
                                                                div()
                                                                    .text_size(crate::ui::design::text_ui())
                                                                    .text_color(crate::ui::design::t3(cx))
                                                                    .child("Grouped by project and agent when Choro can identify ownership. Largest groups first."),
                                                            ),
                                                    )
                                                    .children(process_groups.iter().enumerate().map(
                                                        |(project_index, project)| {
                                                            v_flex()
                                                                .w_full()
                                                                .gap_2()
                                                                .when(project_index > 0, |group| {
                                                                    group
                                                                        .pt_3()
                                                                        .border_t_1()
                                                                        .border_color(
                                                                            crate::ui::design::line(cx),
                                                                        )
                                                                })
                                                                .child(
                                                                    h_flex()
                                                                        .w_full()
                                                                        .min_w(px(0.))
                                                                        .gap_3()
                                                                        .items_center()
                                                                        .child(
                                                                            v_flex()
                                                                                .flex_1()
                                                                                .min_w(px(0.))
                                                                                .gap_0p5()
                                                                                .child(
                                                                                    div()
                                                                                        .truncate()
                                                                                        .text_size(
                                                                                            crate::ui::design::text_body(),
                                                                                        )
                                                                                        .font_weight(
                                                                                            FontWeight::SEMIBOLD,
                                                                                        )
                                                                                        .child(
                                                                                            SharedString::from(
                                                                                                project.name.clone(),
                                                                                            ),
                                                                                        ),
                                                                                )
                                                                                .child(
                                                                                    div()
                                                                                        .text_size(
                                                                                            crate::ui::design::text_ui(),
                                                                                        )
                                                                                        .text_color(
                                                                                            crate::ui::design::t3(cx),
                                                                                        )
                                                                                        .child(format!(
                                                                                            "{} process{}",
                                                                                            project.process_count,
                                                                                            if project.process_count == 1 {
                                                                                                ""
                                                                                            } else {
                                                                                                "es"
                                                                                            },
                                                                                        )),
                                                                                ),
                                                                        )
                                                                        .child(
                                                                            div()
                                                                                .flex_none()
                                                                                .text_size(
                                                                                    crate::ui::design::text_ui(),
                                                                                )
                                                                                .font_weight(
                                                                                    FontWeight::MEDIUM,
                                                                                )
                                                                                .child(Self::format_bytes(
                                                                                    project.memory_bytes,
                                                                                )),
                                                                        )
                                                                        .child(
                                                                            div()
                                                                                .w(px(58.))
                                                                                .flex_none()
                                                                                .text_size(
                                                                                    crate::ui::design::text_ui(),
                                                                                )
                                                                                .text_color(
                                                                                    crate::ui::design::t3(cx),
                                                                                )
                                                                                .child(format!(
                                                                                    "{:.1}%",
                                                                                    project.cpu
                                                                                )),
                                                                        ),
                                                                )
                                                                .children(project.agents.iter().map(
                                                                    |agent| {
                                                                        v_flex()
                                                                            .w_full()
                                                                            .gap_0p5()
                                                                            .child(
                                                                                h_flex()
                                                                                    .w_full()
                                                                                    .min_w(px(0.))
                                                                                    .gap_2()
                                                                                    .items_center()
                                                                                    .px_2()
                                                                                    .py_1()
                                                                                    .rounded(
                                                                                        crate::ui::design::r_sm(),
                                                                                    )
                                                                                    .bg(
                                                                                        crate::ui::design::base(cx)
                                                                                            .opacity(0.4),
                                                                                    )
                                                                                    .child(
                                                                                        div()
                                                                                            .flex_1()
                                                                                            .min_w(px(0.))
                                                                                            .truncate()
                                                                                            .text_size(
                                                                                                crate::ui::design::text_ui(),
                                                                                            )
                                                                                            .font_weight(
                                                                                                FontWeight::MEDIUM,
                                                                                            )
                                                                                            .text_color(
                                                                                                crate::ui::design::accent(cx),
                                                                                            )
                                                                                            .child(
                                                                                                SharedString::from(
                                                                                                    agent.name.clone(),
                                                                                                ),
                                                                                            ),
                                                                                    )
                                                                                    .child(
                                                                                        div()
                                                                                            .flex_none()
                                                                                            .text_size(
                                                                                                crate::ui::design::text_ui(),
                                                                                            )
                                                                                            .text_color(
                                                                                                crate::ui::design::t3(cx),
                                                                                            )
                                                                                            .child(format!(
                                                                                                "{} process{}",
                                                                                                agent.processes.len(),
                                                                                                if agent.processes.len() == 1 {
                                                                                                    ""
                                                                                                } else {
                                                                                                    "es"
                                                                                                },
                                                                                            )),
                                                                                    )
                                                                                    .child(
                                                                                        div()
                                                                                            .w(px(82.))
                                                                                            .flex_none()
                                                                                                .text_size(
                                                                                                    crate::ui::design::text_ui(),
                                                                                                )
                                                                                                .child(Self::format_bytes(
                                                                                                    agent.memory_bytes,
                                                                                                )),
                                                                                    )
                                                                                    .child(
                                                                                        div()
                                                                                            .w(px(58.))
                                                                                            .flex_none()
                                                                                            .text_size(
                                                                                                crate::ui::design::text_ui(),
                                                                                            )
                                                                                            .text_color(
                                                                                                crate::ui::design::t3(cx),
                                                                                            )
                                                                                            .child(format!(
                                                                                                "{:.1}%",
                                                                                                agent.cpu
                                                                                            )),
                                                                                    ),
                                                                            )
                                                                            .children(agent.processes.iter().map(
                                                                                |process| {
                                                                                    h_flex()
                                                                                        .w_full()
                                                                                        .min_w(px(0.))
                                                                                        .min_h(px(28.))
                                                                                        .gap_2()
                                                                                        .items_center()
                                                                                        .pl_3()
                                                                                        .pr_2()
                                                                                        .text_size(
                                                                                            crate::ui::design::text_ui(),
                                                                                        )
                                                                                        .child(
                                                                                            div()
                                                                                                .w(px(82.))
                                                                                                .flex_none()
                                                                                                .font_weight(
                                                                                                    FontWeight::MEDIUM,
                                                                                                )
                                                                                                .child(Self::format_bytes(
                                                                                                    process.memory_bytes,
                                                                                                )),
                                                                                        )
                                                                                        .child(
                                                                                            div()
                                                                                                .w(px(52.))
                                                                                                .flex_none()
                                                                                                .text_color(
                                                                                                    crate::ui::design::t3(cx),
                                                                                                )
                                                                                                .child(format!(
                                                                                                    "{:.1}%",
                                                                                                    process.cpu
                                                                                                )),
                                                                                        )
                                                                                        .child(
                                                                                            div()
                                                                                                .w(px(150.))
                                                                                                .flex_none()
                                                                                                .truncate()
                                                                                                .child(
                                                                                                    SharedString::from(
                                                                                                        process.name.clone(),
                                                                                                    ),
                                                                                                ),
                                                                                        )
                                                                                        .child(
                                                                                            div()
                                                                                                .w(px(76.))
                                                                                                .flex_none()
                                                                                                .text_color(
                                                                                                    crate::ui::design::t3(cx),
                                                                                                )
                                                                                                .child(format!(
                                                                                                    "PID {}",
                                                                                                    process.pid
                                                                                                )),
                                                                                        )
                                                                                        .child(
                                                                                            div()
                                                                                                .flex_1()
                                                                                                .min_w(px(0.))
                                                                                                .truncate()
                                                                                                .text_color(
                                                                                                    crate::ui::design::t4(cx),
                                                                                                )
                                                                                                .child(
                                                                                                    SharedString::from(
                                                                                                        process.command.clone(),
                                                                                                    ),
                                                                                                ),
                                                                                        )
                                                                                },
                                                                            ))
                                                                    },
                                                                ))
                                                        },
                                                    )),
                                            )
                                    }),
                            )
                            .into_any_element()
    }
}
